---
title: "Lista 03 Kaleo256333"
author: "Kaleo Campos"
format: pdf
editor: source
---

## Conexão R >>> SQLite
```{r}
library(DBI)
library(RSQLite)

con <- dbConnect(SQLite(), "me315.sqlite")
```

##SQLite
```{sql connection=con}
SELECT * FROM PRESERVE
```

```{sql connection=con}
SELECT * FROM EMPLOYEE
```

##Hands-On

1. Exiba os valores de `STATE` e `FEE` da tabela `PRESERVE` mas sem duplicados.

```{sql connection=con}
SELECT DISTINCT STATE, FEE FROM PRESERVE
```

2.  Exiba todos os valores de `DNO` na tabela `EMPLOYEE`. Não exiba valores duplicados.

```{sql connection=con}
SELECT DISTINCT DNO FROM EMPLOYEE
```

3.  Execute as `QUERYS` a seguir. Examine as tabelas resultantes e faça as observações relevantes.
  -SELECT DNO, SALARY FROM EMPLOYEE
  -SELECT DISTINCT DNO, SALARY FROM EMPLOYEE
  -SELECT DISTINCT DNO, SALARY FROM EMPLOYEE ORDER BY DNO, SALARY
  
```{sql connection=con}
SELECT DNO, SALARY FROM EMPLOYEE
```

```{sql connection=con}
SELECT DISTINCT DNO, SALARY FROM EMPLOYEE
```

```{sql connection=con}
SELECT DISTINCT DNO, SALARY FROM EMPLOYEE ORDER BY DNO, SALARY
```

Observações:
  -A primeira consulta exibe todas as combinações de departamento e salário de cada funcionário (permitindo duplicatas).

  -A segunda elimina duplicatas idênticas de (DNO, SALARY).

  -A terceira remove duplicatas e ordena o resultado em ordem crescente por DNO e SALARY.

4.  Exiba todas as informações sobre qualquer reserva natural em Montana que seja menor que 1.000 acres.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE = 'MT' AND ACRES < 1000
```

5.  Exiba todas as informações sobre qualquer reserva natural cujo valor de `ACRES` esteja entre 1200 e 15000, inclusive.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE ACRES BETWEEN 1200 AND 15000
```

6.  Exiba todas as informações sobre qualquer reserva natural localizada em Montana que não possua taxa de entrada e seja maior que 10.000 acres.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE = 'MT' AND FEE = 0 AND ACRES > 10000
```

7.  Exiba todas as informações sobre as reservas naturais localizadas em Montana ou Massachusetts.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE IN ('MT', 'MA')
```

8.  Exiba todas as informações sobre qualquer reserva natural localizada em Montana ou qualquer reserva que seja menor que 1.000 acres.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE = 'MT' OR ACRES < 1000
```

9.  Exiba o número e o nome de qualquer reserva natural que possua taxa de entrada que não seja igual a zero.

```{sql connection=con}
SELECT PNO, PNAME FROM PRESERVE
WHERE FEE <> 0
```

10. Exiba o número e o nome das reservas naturais que não possuem taxa de entrada de US$ 3,00 e não possuem taxa de US$ 10,00.

```{sql connection=con}
SELECT PNO, PNAME FROM PRESERVE
WHERE FEE NOT IN (3.00, 10.00)
```

11. Exiba todas as informações sobre qualquer reserva natural localizada no Arizona que não possua taxa de entrada, ou qualquer reserva que seja menor que 100 acres (independentemente de seus valores de `STATE` e `FEE`).

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE (STATE = 'AZ' AND FEE = 0) OR ACRES < 100
```

12. Exiba todas as informações sobre qualquer reserva natural que seja menor que 1.000 acres e tenha taxa de entrada de zero dólares ou esteja localizada no Arizona.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE ACRES < 1000 AND (FEE = 0 OR STATE = 'AZ')
```

13. Selecione todas as informações sobre qualquer reserva natural com taxa de entrada que não seja maior que zero, ou qualquer outra reserva, independentemente de sua taxa, que esteja localizada em Montana e seja maior que 1.000 acres.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE FEE <= 0 OR (STATE = 'MT' AND ACRES > 1000)
```

14. Exiba todas as informações sobre todas as reservas naturais, exceto aquelas reservas de Montana sem taxa de entrada.

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT (STATE = 'MT' AND FEE = 0)
```

15. As seguintes cláusulas `WHERE` são logicamente equivalentes?
  -WHERE STATE = 'MA' AND (ACRES > 1000 OR FEE = 0.0)
  -WHERE (STATE = 'MA' AND ACRES > 1000) OR (STATE = 'MA' AND FEE = 0.0)

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE = 'MA' AND (ACRES > 1000 OR FEE = 0.0)
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE (STATE = 'MA' AND ACRES > 1000) OR (STATE = 'MA' AND FEE = 0.0)
```

Sim, são logicamente equivalentes, aplica-se a propriedade distributiva do operador AND em relação ao OR.

16. As seguintes cláusulas WHERE são logicamente equivalentes?
  -WHERE STATE = 'MA' OR (ACRES > 1000 AND FEE = 0.0)
  -WHERE (STATE = 'MA' OR ACRES > 1000) AND (STATE = 'MA' OR FEE = 0.0)

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE STATE = 'MA' OR (ACRES > 1000 AND FEE = 0.0)
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE (STATE = 'MA' OR ACRES > 1000) AND (STATE = 'MA' OR FEE = 0.0)
```

Sim, são logicamente equivalentes, aplica-se a propriedade distributiva do operador OR em relação ao AND.

17. As seguintes cláusulas WHERE são logicamente equivalentes?
  -WHERE NOT (ACRES < 50 AND STATE = 'MA')
  -WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
  -WHERE ACRES >= 50 OR STATE <> 'MA'
  
```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT (ACRES < 50 AND STATE = 'MA')
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE ACRES >= 50 OR STATE <> 'MA'
```

Não, as três cláusulas não são logicamente equivalentes entre si. Pela regra mostrada NOT (C1 AND C2) = (NOT C1) OR (NOT C2). 
A expressão NOT (ACRES < 50 AND STATE = 'MA') resulta em NOT ACRES < 50 OR NOT STATE = 'MA', o que é idêntico a ACRES >= 50 OR STATE <> 'MA'. 
A 1ª e a 3ª cláusulas são equivalentes. 
A 2ª cláusula está incorreta por usar o operador AND em vez de OR.

18. As seguintes cláusulas WHERE são logicamente equivalentes?
  -WHERE NOT (ACRES < 50 OR STATE = 'MA')
  -WHERE NOT ACRES < 50 OR NOT STATE = 'MA'
  -WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
  
```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT (ACRES < 50 OR STATE = 'MA')
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT ACRES < 50 OR NOT STATE = 'MA'
```

```{sql connection=con}
SELECT * FROM PRESERVE
WHERE NOT ACRES < 50 AND NOT STATE = 'MA'
```

Não, as três não são equivalentes entre si. Pela regra mostrada NOT (C1 OR C2) = (NOT C1) AND (NOT C2).
A expressão NOT (ACRES < 50 OR STATE = 'MA') resulta em NOT ACRES < 50 AND NOT STATE = 'MA'.
A 1ª e a 3ª cláusulas são equivalentes.
A 2ª cláusula está incorreta por usar o operador OR em vez de AND.